version: "3.9"
services:
  backend:
    image: ${REGISTRY}/azimuth:${BACKEND_VERSION}_${DEVICE}
    environment:
      - "CFG_PATH=${CFG_PATH}"
      - "LOAD_CONFIG_HISTORY=${LOAD_CONFIG_HISTORY}"
      - "HF_HOME=/azimuth_shr/huggingface_cache"
      - "SENTENCE_TRANSFORMERS_HOME=/azimuth_shr/sentence_transformers"
      - "TFHUB_CACHE_DIR=/azimuth_shr/tf_hub"
      - "TH"
      - "TEMP"
      - "NAME"
      - "BEHAVIORAL_TESTING"
      - "SIMILARITY"
    volumes:
    - ./config:/config
    - ./azimuth_shr:/azimuth_shr
    - ./cache:/cache
  web:
    image: "${REGISTRY}/azimuth-app:${FRONTEND_VERSION}"
    command:
      - node
      - ./server.js
    environment:
      - "PORT=8080"
    ports:
      - "8080:8080"
    links:
      - backend:host.docker.internal
