# Minimal makefile for documentation

.PHONY: build_docs
build_docs:
	docker build -t $(REGISTRY)/$(IMAGE)_docs -f docs/Dockerfile.docs .

.PHONY: push_docs
push_docs:
	docker push $(REGISTRY)/$(IMAGE)_docs

.PHONY: serve_docs
serve_docs:
	docker run -p 8080:8080 --rm -it $(REGISTRY)/$(IMAGE)_docs
