site_name: Azimuth documentation
repo_url: https://github.com/ServiceNow/azimuth
edit_uri: edit/main/docs/docs/
plugins:
  - search
extra:
  version:
    provider: mike
    default: main
theme:
  name: material
  custom_dir: overrides
  logo: _static/azimuth_icon_white.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.suggest
    - navigation.indexes
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # Page tree
nav:
  - Home:
      - index.md
      - about-us.md
  - Getting Started:
      - getting-started/index.md
      - getting-started/a-install.md
      - getting-started/b-basics.md
      - getting-started/c-run.md
      - Changelog:
          - Releases: getting-started/changelog.md
  - Key Concepts:
      - key-concepts/index.md
      - key-concepts/smart-tags.md
      - key-concepts/proposed-actions.md
      - key-concepts/outcomes.md
      - Analyses:
          - key-concepts/saliency.md
          - key-concepts/syntax-analysis.md
          - key-concepts/similarity.md
          - key-concepts/behavioral-testing.md
          - key-concepts/uncertainty.md
  - User Guide:
      - Dashboard:
          - user-guide/index.md
          - user-guide/dataset-warnings.md
          - user-guide/behavioral-testing-summary.md
          - user-guide/post-processing-analysis.md
      - Exploration Space:
          - user-guide/exploration-space/index.md
          - user-guide/exploration-space/performance-overview.md
          - user-guide/exploration-space/confusion-matrix.md
          - user-guide/exploration-space/utterances-table.md
          - user-guide/exploration-space/utterance-details.md
      - user-guide/settings.md
      - user-guide/custom-utterances.md
  - Reference:
      - reference/index.md
      - Configuration:
          - reference/configuration/index.md
          - reference/configuration/project.md
          - reference/configuration/model_contract.md
          - reference/configuration/common.md
          - Analyses Customization:
              - reference/configuration/analyses/index.md
              - reference/configuration/analyses/behavioral_testing.md
              - reference/configuration/analyses/similarity.md
              - reference/configuration/analyses/dataset_warnings.md
              - reference/configuration/analyses/syntax.md
      - Custom Objects:
          - reference/custom-objects/index.md
          - reference/custom-objects/dataset.md
          - reference/custom-objects/model.md
          - reference/custom-objects/postprocessors.md
          - reference/custom-objects/metric.md
  - Development:
      - development/index.md
      - development/setup.md
      - development/launching.md
      - development/dev-practices.md
