name: Docker
on:
  push:
    tags:
      - "v*"
jobs:
  docker-deploy-cpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push CPU Docker image
        run: |
          make DEVICE=cpu build push
          make DEVICE=cpu TAG=$VERSION build push
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
  docker-deploy-gpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push GPU Docker image
        run: |
          make DEVICE=gpu build push
          make DEVICE=gpu TAG=$VERSION build push
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

