name: Docker CPU
on:
  push:
    tags:
      - "v*"
jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
         make DEVICE=cpu build push
         make TAG=$VERSION DEVICE=cpu build push
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

