name: documentation
on:
  push:
    branches:
      - main
      - features/versioning
    tags:
      - "v*"
      - "test*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Github"
        run: |
          git fetch origin gh-pages --depth=1
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: "on tags"
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pip install mkdocs-material mike
          cd docs && mkdocs build && mike set-default --push main && mike deploy --push --force $VERSION
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: "on branch"
        if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
        run: |
          pip install mkdocs-material mike
          cd docs && mkdocs build && mike set-default --push main && mike deploy --push --force main
